**question1**

In [ ]:
import numpy as np
n=int(input("enter the number of stars: "))
a=np.zeros((n,n))
print(a)

for i in range(len(a)):
  for j in range(len(a)):
    if i==j or j==((n-1)-i):
      a[i][j]=1
    if i==0 or i==(n-1) or j==0 or j==(n-1):
      a[i][j]=1
print(a)

for i in range(len(a)):
  print("\n")
  for j in range(len(a)):
    if a[i][j]==1:
      print('*',end=" ")
    else:
      print(" ",end=" ")


enter the number of stars: 8
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 0. 1. 1.]
 [1. 0. 1. 0. 0. 1. 0. 1.]
 [1. 0. 0. 1. 1. 0. 0. 1.]
 [1. 0. 0. 1. 1. 0. 0. 1.]
 [1. 0. 1. 0. 0. 1. 0. 1.]
 [1. 1. 0. 0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


* * * * * * * * 

* *         * * 

*   *     *   * 

*     * *     * 

*     * *     * 

*   *     *   * 

* *         * * 

* * * * * * * * 

Q2.1

In [ ]:
import numpy as np
import random

article = ['the', 'a', 'one', 'some', 'any']
noun = ['boy', 'girl', 'dog', 'town', 'car', 'table']
verb = ['drove', 'jumped', 'ran', 'walked', 'skipped', 'passed']
preposition = ['to', 'from', 'over', 'under', 'on']

article=np.array(article)
noun=np.array(noun)
verb=np.array(verb)
preposition=np.array(preposition)

m=0
while m!=20:
  senti=[]
  senti.append(article[random.randint(0,int(len(article)-1))])
  senti.append(noun[random.randint(0,int(len(noun)-1))])
  senti.append(verb[random.randint(0,int(len(verb)-1))])
  senti.append(preposition[random.randint(0,int(len(preposition)-1))])
  senti.append(article[random.randint(0,int(len(article)-1))])
  senti.append(noun[random.randint(0,int(len(noun)-1))])
  m +=1
  #print("\n")
  for i in range(len(senti)):
    if i==0:
      f=senti[0]
      f=f.replace(f[0],f[0].upper())
      print(f,end=' ')
      #print(senti[0][0].upper())
    elif i==(len(senti)-1):
      print(senti[-1]+".")
    else:
      print(senti[i],end=" ")

Any boy ran under a town.
The dog walked under any car.
Any dog jumped over some boy.
One car drove under any car.
Some town passed over any car.
Some boy jumped over any table.
One table walked on any girl.
A car walked to some car.
Some table ran under any boy.
The girl walked under the town.
Some dog ran under the car.
One car passed on a girl.
Some boy ran from some car.
A car drove under any town.
The town jumped to one town.
A town skipped from the boy.
Some dog skipped under some car.
The town drove over any town.
One town jumped on a dog.
Any car walked on a town.


Q2.2

In [ ]:
import numpy as np
import random

Q=int(input("enter the number of sentences: "))

article = ['the', 'a', 'one', 'some', 'any']
noun = ['boy', 'girl', 'dog', 'town', 'car', 'table']
verb = ['drove', 'jumped', 'ran', 'walked', 'skipped', 'passed']
preposition = ['to', 'from', 'over', 'under', 'on']

article=np.array(article)
noun=np.array(noun)
verb=np.array(verb)
preposition=np.array(preposition)
print("\n")
m=0
while m!=Q:
  senti=[]
  senti.append(article[random.randint(0,int(len(article)-1))])
  senti.append(noun[random.randint(0,int(len(noun)-1))])
  senti.append(verb[random.randint(0,int(len(verb)-1))])
  senti.append(preposition[random.randint(0,int(len(preposition)-1))])
  senti.append(article[random.randint(0,int(len(article)-1))])
  senti.append(noun[random.randint(0,int(len(noun)-1))])
  m +=1
  #print("\n")
  for i in range(len(senti)):
    if i==0:
      f=senti[0]
      f=f.replace(f[0],f[0].upper())
      print(f,end=' ')
      #print(senti[0][0].upper())
    elif i==(len(senti)-1):
      if m%2==0:
        print(senti[-1]+"!",end=" ")
      else:
        print(senti[-1]+".",end=" ")

    else:
      print(senti[i],end=" ")

enter the number of sentences: 10


Any girl skipped on any car. Any boy drove under any boy! A dog passed under any dog. A boy passed on the car! A car passed under a girl. One town jumped on a girl! One town drove over some girl. A car walked on the boy! A table walked to a car. The dog jumped over one dog! 